spring:
  config:
    activate:
      on-profile: dev
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

vitalirspring:
  enable-swagger-security: false
  enable-actuator-security: false
  enable-csrf: false
