spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: vitalir
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/vitalirspring
    password: 12345

vitalirspring:
  enable-swagger-security: true
  enable-csrf: true
jwt_secret: default
