spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: vitalir
    url: jdbc:postgresql://localhost:5432/vitalirspring

vitalirspring:
  enable-swagger-security: true
  enable-csrf: true
jwt_secret: default
