spring.profiles.active: "dev"
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: vitalir
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/vitalirspring
    password: 12345

jwt_secret: default
